### PR TITLE
Support for Safari

### PR DESCRIPTION
**Pull request by ken-matsui**
This PR brings support of Safari by using [`safari-web-extension-converter`](https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari).  If you have macOS PC, you can release it on [App Store](https://apps.apple.com/us/story/id1377753262); also, [this article]() might be useful for you if you are highly motivated to do that. I would appreciate it if you could do that. If you do not want because of Apple Developer Program, I would like to install this as a Safari Web Extension personally, and I think README.md should be updated.

Moreover, one thing that you should know is that Safari has less storage than the other browsers even though you specified `unlimitedStorage` in [manifest.json](https://github.com/wtetsu/mouse-dictionary/blob/e596dd44bf0a654ed889beeb476b31dd20a5e787/static/manifest.json#L11). Apple states the local storage limit is 5 MB, and unlimited storage permission increases limit to 10 MB ([ref](https://developer.apple.com/documentation/safariservices/safari_web_extensions/assessing_your_safari_web_extension_s_browser_compatibility#3584139)). However, this storage is so few that large-size dictionaries like `EIJIRO-1448` could not have been loaded due to storage quota exceed.

regarding to: #25

### CODE REVIEW

**Comment by wtetsu** [comment]
Aside from lack of my current motivation to publish it on App Store, supporting Safari build sounds like a great idea. Let me try the Safari build soon on my MacBook.
By the way, could you please share "this article" again? The link looks broken.

**Comment by ken-matsui** [comment]
@wtetsu 
Thank you for your response, and I am sorry for sending you a broken link. The following link is what I wanted to send you.
> https://developer.apple.com/safari/extensions

**Comment by wtetsu** [comment]
@ken-matsui 

Hi, were you able to build the Actions' artifact dist-safari, and installed Mouse Dictionary on your Safari?

https://github.com/wtetsu/mouse-dictionary/actions/runs/450896512

I faced two types of errors.

## Error 1

```
error: ~/dist-safari-tmp/options: No such file or directory
```

To place mouse-dictionary build directory on my home directory resolved it,
but I think this workaround is strange and not reasonable for normal developers.


## Error 2

`Unknown attribute 'main'`

Probably, this is due to my old Xcode.

----

- macOS 10.13
- Xcode 10.2.1

**Comment by ken-matsui** [comment]
@wtetsu 
I apologize for replying late.

## Error 1
I also got the same error with Error 1. To build by `safari-web-extension-converter`, I had had to build to Chrome Extension (it is `dist-safari-tmp`) and then convert it using `safari-web-extension-converter` (it will be placed in `dist-safari`). However, I did not know `dist-safari` refers `dist-safari-tmp`, and this is the reason for Error 1. Therefore, I pushed a new commit to fix the problem. Could you please check it again?

## Error 2
I did not see the same error, so it seems your Xcode is old. For your information, the following is my environment versions.

* macOS 11.1
* Xcode 12.3

**Comment by wtetsu** [comment]
@ken-matsui 

Thank you for resolving the issues.

1 -> I made sure it has been resolved
2 -> I succeeded to build it using `@NSApplicationMain`

Due to personal reasons, I cannot update macOS and Xcode,
but I made sure builds succeeded so I'll merge this Safari support as an experimental feature.

---

Before merging it, would you please delete .DS_Store?
(Please remove it from the history and force-push it)

**Comment by ken-matsui** [comment]
@wtetsu 

Thank you so much for your review. I removed `.DS_Store` and force-pushed it.

**Comment by wtetsu** [comment]
Thank you!
I've merge and added some information README.

**Pull request merged**
