### PR TITLE
generate release archives. (npm run archive)

### PR DESCRIPTION
**Pull request by MichinariNukazawa**
`npm run archive` generate uploadable zip package for stores(ChromeWebStore, addons.mozilla.org)

### CODE REVIEW

**Comment by wtetsu** [comment]
Thank you!
Could you please resolve the conflicts?

**Comment by MichinariNukazawa** [comment]
conflict resolved (and CI excluded).

**Comment by wtetsu** [comment]
Thank you!

I think it's a good idea to add scripts that don't depend on the platform tools for ceating archive for publishing. But I want to introduce some modifications by myself to your commits in order to follow the project style structure. Please execuse.

**Comment by MichinariNukazawa** [comment]
Thanks modification and merge!

**Pull request merged**
